
[
    'skip' => 'Skip to main content',        
    'close-search' => 'Close Search',        
    'Development' => 'Development', 
    'Service' => 'Service',    
    'professional' => 'Professional Website Agency Services',
    'projects-completed' => 'Over 1,000 projects completed!',
    

    'web-agency' => 'Website Agency Service', 
    'all-devices' => 'Works on All Devices',  
    'we-can' => 'We can create a website',  
    'we-can2' => 'for companies, corporate entities, schools, churches, online advertising agencies, restaurants, shopping malls, law firms, hospitals, and professional services, ensuring each client receives a customized and effective online presence.',
    
    
    'procedures' => 'Planned Procedures',   
    'elevate-your-presence' => 'Elevate your online presence with our planned website development service.',
    'form-concept' => 'From concept to launch',     
    'we' => 'we',      
    'strategize' => 'strategize every step',       
    'ensure' => 'to ensure your website embodies your vision, engages your audience, and',
    

    'success' => 'drives success',    
    'digital-realm' => 'in the digital realm.',      
    'procedure' => 'Website Creation Procedure',        
    'start' => 'Start the Project!',         
    'discuss' => 'Discussing',       
    'projects-details' => 'the project and its details.',        
    'Research' => 'Research',       
    'conduct' => 'Conduct research to',      
    'gather' => 'gather ideas',      
    'about' => 'about your ',        
    'business-in' => 'business industry',        
    'and' => 'and',     
    'competitors' => 'competitors',      



    'Strategy' => 'Strategy & Branding',         
    'keywords' => 'Select keywords',         
    'establish' => 'establish a',      
    'guide' => 'style guide',        
    'determine' => 'and determine the ',   
    'layout' => 'layout',       
    'mockup' => 'Mockup & Adjustments',      
    'Prepare' => 'Prepare the website',      
    'mockup' => 'mockup',        
    'make' => 'and make necessary',      
    'adjustments' => 'adjustments',      
    'obtain' => 'and obtain',        
    'confirmation' => 'confirmation',        
    'Development' => 'Development',      
    'Initiate' => 'Initiate the',       
    'dev-web' => 'development of the website',       
    'config' => 'Adjustments & Final Configuration',        
    'Implement' => 'Implement',     
    'adjustments' => 'adjustments',      
    'and' => 'and',      
    'confirm' => 'confirm',     
    'the' => 'the',      
    'finalized' => 'finalized website.',         


    'publishing' => 'Publishing!',  
    'Launch ' => 'Launch ', 
    'the-web' => ' the website to the',  
    'public' => 'public',    
    'maintain' => 'Free Maintenance',    
    'Complimentary' => 'Complimentary maintenance',  
    'for' => 'for',  
    'months' => 'months',    
    'during' => 'during which you can request',  
    'simple-text' => 'simple text',  
    'and ' => 'and ',   
    'image' => 'image', 
    'changes' => 'changes from us.',    
    'Web-Design' => 'Web Design',    
    'crafts' => 'Codibu crafts websites by ',    
    'brand' => 'brand guidelines',   
    'ensuring ' => 'ensuring',  
    'quality' => 'efficiency and superior quality',  
    'saving' => 'saving you valuable time while maintaining brand consistency.',
    

    'powerful' => 'Powerful CMS &amp; CRM',      
    'From' => 'From',        
    'blogs' => 'personal blogs',        
    'to' => 'to',       
    'enterprise' => 'enterprise-level websites',         
    'offers' => 'Codibu offers versatility and scalability,      
                providing robust solutions adaptable to the  
                needs of individuals and ',    
    'large' => 'large corporations',         
    'alike' => 'alike, ensuring an exceptional online experience across',      
    'scale' => 'every scale of operation',      

    'demo' => 'Restaurant Demo',     
    'demo2' => 'E-commerce (Online Shop) Demo',  
    'save_time' => 'Save Time & Money!',     
    'unlock' => 'Unlock',  
    'limitless' => 'limitless',  
    'growth' => 'growth opportunities for your business with Codibu, empowered by its vast array of',

    'customizable' => 'plugins and fully customizable system.',     
    'unlock2' => 'Unlock the advantages of',         
    'hassle' => 'hassle-free maintenance',       
    'and' => 'and',      
    'low-costs' => 'low operational costs',     
    'with' => 'with Codibu.',        
    'utilize' => 'Numerous prominent and leading companies utilize',

    'wordPress ' => 'WordPress ',   
    'landscape' => 'in today’s digital landscape.',
    'law' => 'It's the law!',  
    'compliance' => 'ADA Compliance',    
    'ensuring' => 'Ensuring compliance with',   
    'regulations' => 'ADA regulations', 
    'set' => 'set forth by the',    
    'us-gov' => 'US government,',   
    'crucial' => 'it's crucial to proactively address accessibility concerns to avoid potential',
   
    'challenges' => 'legal challenges', 
    'disabilities' => 'from individuals with disabilities.',    
    
    'delivered' => 'What We Delivered',    
    'completed' => 'Codibu has completed',      
    'projects_num' => '1000+ projects', 
    'past' => ' in the past',  
    
    'year_num' => '20 years',       
    'check_live' => 'Check 600+ Live Templates',         
    'work_together' => 'Let's work together!',       
    'reach' => 'Reach out to us today for a',      
    'estimate' => 'free website project estimate.',     
    'placeholder1' => 'Your Name',     
    'placeholder2' => 'Your Contact Information',        
    'inquiry' => 'inquiry',     
    'close_menu' => 'Close Menu',       
    'services' => 'Services',      
    'hosting' => 'Website Hosting',     
    'domain' => 'Website Domain',      
    'web-dev' => 'Website Development',      
    'online_marketing' => 'Online Marketing',       
    'pricing' => 'Pricing & Plans',      
    'quote' => 'Free Quote',        

]