
[
'skip' => '주요 콘텐츠로 건너뛰기',
'close-search' => '검색 닫기',
'Development' => '개발',
'Service' => '서비스',
'professional' => '전문 웹사이트 대행 서비스',
'projects-completed' => '1,000개 이상의 프로젝트가 완료되었습니다!',
'web-agency' => '홈페이지 대행 서비스',
'all-devices' => '모든 장치에서 작동',
'we-can' => '우리는 웹사이트를 만들 수 있어요',
'we-can2' => '회사, 기업체, 학교, 교회, 온라인 광고 대행사, 레스토랑, 쇼핑몰, 법률 회사, 병원 및 전문 서비스를 위해 각 고객이 맞춤화되고 효과적인 온라인 존재를 받을 수 있도록 보장합니다.',


'procedures' => '계획된 절차',
'elevate-your-presence' => '우리가 계획한 웹사이트 개발 서비스를 통해 귀하의 온라인 인지도를 높이십시오.',
'form-concept' => '컨셉부터 출시까지',
'we' => '우리',
'strategize' => '모든 단계에서 전략을 세우다',
'ensure' => '귀하의 웹사이트가 귀하의 비전을 구현하고 청중의 참여를 유도하며',
'success' => '성공을 주도하다',
'digital-realm' => '디지털 영역에서.',
'procedure' => '웹사이트 생성 절차',
'start' => '프로젝트를 시작하세요!',
'discuss' => '토론',
'projects-details' => '프로젝트와 그 세부 사항.',
'Research' => '연구',
'conduct' => '연구를 수행하다',
'gather' => '아이디어를 모으다',
'about' => '당신에 대해',
'business-in' => '비즈니스 산업',
'and' => '그리고',
'competitors' => '경쟁자',



'Strategy' => '전략 및 브랜딩',
'keywords => '키워드 선택',
'establish' => '설립하다',
'guide' => '스타일 가이드',
'determine' => '그리고 결정',
'layout' => '공들여 나열한 것',
'mockup' => '모형 및 조정',
'Prepare' => '웹사이트 준비',
'mockup' => '모형',
'make' => '그리고 필요하게 만들어',
'adjustments' => '조정',
'obtain' => '그리고 획득',
'confirmation' => '확인',
'Development' => '개발',
'Initiate' => '시작하다',
'dev-web' => '웹사이트의 개발',
'config' => '조정 및 최종 구성',
'Implement' => '구현하다',
'adjustments' => '조정',
'and' => '그리고',
'confirm' => '확인하다',
'the' => '그만큼',
'finalized' => '최종 홈페이지.',


'publishing' => '출판!',
'Launch ' => '시작하다',
'the-web' => '웹사이트에서',
'public' => '공공의',
'maintain' => '무료 유지보수',
'Complimentary' => '무료 유지보수',
'for' => '~을 위한',
'months' => '개월',
'during' => '그 동안 요청할 수 있습니다',
'simple-text' => '간단한 텍스트',
'and ' => '그리고',
'image' => '영상',
'changes' => '우리에게서 변화.',
'Web-Design' => '웹 디자인',
'crafts' => 'Codibu 공예품 웹사이트',
'brand' => '브랜드 가이드라인',
'ensuring ' => '보장',
'quality' => '효율성과 우수한 품질',
'saving' => '브랜드 일관성을 유지하면서 귀중한 시간을 절약해 보세요.',
'powerful' => '강력한 CMS &amp; CRM',
'From' => '에서',
'blogs' => '개인 블로그',
'to' => '에게',
'enterprise' => '기업 수준 웹사이트',
'offers' => 'Codibu는 다양성과 확장성을 제공합니다.
다음에 적응할 수 있는 강력한 솔루션을 제공합니다.
개인의 필요와',
'large' => '대기업',
'alike' => '마찬가지로, 전 세계에서 탁월한 온라인 경험을 보장합니다.',
'scale' => '모든 규모의 운영',


'demo' => '레스토랑 데모',
'demo2' => '전자상거래(온라인 상점) 데모',
'save_time' => '시간과 돈을 절약하세요!',
'unlock' => '터놓다',
'limitless' => '무한한',
'growth' => '광범위한 기능을 갖춘 Codibu와 함께 귀하의 비즈니스 성장 기회를 얻으세요',
'customizable' => '플러그인과 완전히 사용자 정의 가능한 시스템.',
'unlock2' => '장점을 활용하세요',
'hassle' => '번거롭지 않은 유지 관리',
'and' => '그리고',
'low-costs' => '낮은 운영 비용',
'with' => '코디부와 함께.',
'utilize' => '수많은 유명 기업들이 활용하고 있습니다.',
'wordPress ' => '워드프레스',
'landscape' => '오늘날의 디지털 환경에서.',
'law' => '그것은 법이다!',
'compliance' => 'ADA 규정 준수',
'ensuring' => '규정 준수 보장',
'regulations' => 'ADA 규정',
'set' => '에 의해 설정된',
'us-gov' => '미국 정부,',
'crucial' => '잠재적인 문제를 방지하려면 접근성 문제를 사전에 해결하는 것이 중요합니다.',
'challenges' => '법적 문제',
'disabilities' => '장애인으로부터.',


'delivered' => '우리가 제공한 것',
'completed' => '코디부가 완성했어요',
'projects_num' => '1000개 이상의 프로젝트',
'past' => '과거에',

'year_num' => '20 년',
'check_live' => '600개 이상의 라이브 템플릿을 확인하세요',
'work_together' => '같이 일하자!',
'reach' => '오늘 우리에게 연락하세요.',
'estimate' => '무료 웹사이트 프로젝트 견적.',
'placeholder1' => '당신의 이름',
'placeholder2' => '귀하의 연락처 정보',
'inquiry' => '문의',
'close_menu' => '메뉴 닫기',
'services' => '서비스',
'hosting' => '웹사이트 호스팅',
'domain' => '웹사이트 도메인',
'web-dev' => '웹사이트 개발',
'online_marketing' => '온라인 마케팅',
'pricing' => '가격 및 계획',
'quote' => '무료 견적',


]